In [ ]:
!pip install torch numpy --quiet

In [ ]:
import torch


In [ ]:
# Number

t1 = torch.tensor(4.)

In [ ]:
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
#vector
t2=torch.tensor([1. , 2 , 3 , 4])

In [ ]:
t2

tensor([1., 2., 3., 4.])

In [ ]:
t2[2]

tensor(3.)

In [ ]:
t2[2].dtype

torch.float32

In [ ]:
#matrics

t3 = torch.tensor([[1. , 2, 3],
                  [4 , 5 , 6],
                  [7,  8,  9]])

In [ ]:
t3

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# 3-dimensional array

t4 = torch.tensor([[[1., 2., 3.],
                   [4., 5., 6],
                   [7., 8, 9.]],
                  [[11., 12., 3.],
                   [14., 15., 16.],
                   [7, 18., 9]]])

In [ ]:
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[11., 12.,  3.],
         [14., 15., 16.],
         [ 7., 18.,  9.]]])

In [ ]:
# lets check the shap of the tensors

t1.shape


torch.Size([])

In [ ]:
t2.shape

torch.Size([4])

In [ ]:
t3.shape

torch.Size([3, 3])

In [ ]:
t4.shape

torch.Size([2, 3, 3])

In [ ]:
# create tensors

x = torch.tensor(3.)
w = torch.tensor(4. , requires_grad=True)
b = torch.tensor(5. , requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmetic operations

y = w * x + b

y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# compute derivative

y.backward()

In [ ]:
# Display Gradient

print('dy/dx' , x.grad)
print('dy/dw' , w.grad)
print('dy/db' , b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])

x

array([[1, 2],
       [3, 4]])

In [ ]:
#conver the numpy array to a torch tensor.

y = torch.from_numpy(x)

y

tensor([[1, 2],
        [3, 4]])

In [ ]:
x.dtype , y.dtype

(dtype('int64'), torch.int64)

In [ ]:
# Convert a torch tensor to an numpy array

z = y.numpy()

z

array([[1, 2],
       [3, 4]])

In [ ]:
# for save

!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-pytorch-basics-live')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


In [ ]:
##########################################
######  Linear Regression and Gradient Decent ############
##########################################

In [ ]:
###########Input (Tempreture , Rainfall , Humidity)
import numpy as np
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [ ]:
##########Target Variables (Apples , Oranges)

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = 'float32')

In [ ]:
########## Convert numpy arrays into tensor
import torch
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
##########  Weights and biases

w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w)
print(b)

tensor([[-1.4203, -1.2439, -0.6284],
        [ 1.4117, -0.4268,  2.9631]], requires_grad=True)
tensor([-1.8221,  0.4758], requires_grad=True)


In [ ]:
############ matrics multiplication & transport of weight matric using model method

def model(x):
  return x @ w.t() + b



In [ ]:
w.t()

tensor([[-1.4203,  1.4117],
        [-1.2439, -0.4268],
        [-0.6284,  2.9631]], grad_fn=<TBackward0>)

In [ ]:
inputs @ w.t() +b

tensor([[-215.8667,  202.3493],
        [-280.7504,  281.0230],
        [-328.5177,  237.9650],
        [-223.4320,  235.7524],
        [-263.2250,  264.3304]], grad_fn=<AddBackward0>)

In [ ]:
#################  Genrate Predictions   ##############

preds = model(inputs)
print(preds)

tensor([[-215.8667,  202.3493],
        [-280.7504,  281.0230],
        [-328.5177,  237.9650],
        [-223.4320,  235.7524],
        [-263.2250,  264.3304]], grad_fn=<AddBackward0>)


In [ ]:
 ############# Now compare with targets for the right predictions

 print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [ ]:
############  Loss Function   #############

### Before we improve our model, we need a way to evaluate how well our model
### is performing. we can compare the models predictions with the actual targets using the following method.
### 1. calculate the diffrence between the two matrics (preds and targets)
### 2. square all elements of the diffrence matrics to remove negative values
### 3. caculate the result of elements in the resulting matrics
### 4. the result is a single number known as the mean squared error (MSE)



In [ ]:
### diffrence between actual and predicted values
diff = preds - targets
# diff * diff => remove negative values
# torch.sum(diff * diff)/diff.numel  => sum and average of the square values

In [ ]:
# MSE LOSS

def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff)/diff.numel()

In [ ]:
############ Compute Loss ##############

loss = mse(preds , targets)

print(loss)

tensor(72097.0234, grad_fn=<DivBackward0>)


In [ ]:
###############  compute gradients

loss.backward()

In [ ]:
############## Gradients for weights

print(w)
print(w.grad)

tensor([[-1.4203, -1.2439, -0.6284],
        [ 1.4117, -0.4268,  2.9631]], requires_grad=True)
tensor([[-28400.6367, -31145.5312, -19103.0117],
        [ 13095.2178,  12254.5615,   8165.4863]])


In [ ]:
############## Gradients for baises

print(b)
print(b.grad)

tensor([-1.8221,  0.4758], requires_grad=True)
tensor([-338.5583,  152.2840])


In [ ]:
######### when one pass is complete then we have to clear weight and baises zero using .zero_() method

w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
#######   Adjest weights and biases using gadient descent (optimization technique)

# 1. generate predictions
# 2. calculate the loss
# 3. compute gradients w.r.t the weights and biases
# 4. adjust the wieghts by subtracting a small quantity proportional to the gradient
# reset the gradients to zero



In [ ]:
########## Generate Predictions
preds = model(inputs)
print(preds)


tensor([[-215.8667,  202.3493],
        [-280.7504,  281.0230],
        [-328.5177,  237.9650],
        [-223.4320,  235.7524],
        [-263.2250,  264.3304]], grad_fn=<AddBackward0>)


In [ ]:
######### Calculate the loss
loss = mse(preds , targets)
print(loss)

tensor(72097.0234, grad_fn=<DivBackward0>)


In [ ]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-28400.6367, -31145.5312, -19103.0117],
        [ 13095.2178,  12254.5615,   8165.4863]])
tensor([-338.5583,  152.2840])


In [ ]:
####### Adjust Weights & reset gradients
with torch.no_grad():    # it means that should not track , calculate, or modify gradients while updating the weights and biases. we just want to use the gradints values.
   w -=  w.grad * 1e-5
   b -=  b.grad * 1e-5      # b = b-b.grad
   w.grad.zero_()
   b.grad.zero_()

In [ ]:
print(w)
print(b)

tensor([[-1.1363, -0.9324, -0.4374],
        [ 1.2807, -0.5493,  2.8815]], requires_grad=True)
tensor([-1.8188,  0.4743], requires_grad=True)


In [ ]:
#### claculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(49060.7422, grad_fn=<DivBackward0>)


In [ ]:
#########  Train for 100 epochs  #########    to reduce the loss further , we can repeat the process of adjusting the weight and biasess using the gradients multiple times.

########  Each itration is called epoch.  let's train the model for 100 epochs.

for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
#### once again, let's verify that the loss is now lower:

### calculate loss

preds = model(inputs)
loss = mse(preds , targets)

print(loss)

tensor(516.2106, grad_fn=<DivBackward0>)


In [ ]:
#### Predictions

preds

tensor([[ 59.8973,  76.9731],
        [ 83.1687, 118.8061],
        [112.1075,  80.9995],
        [ 38.6272,  76.6721],
        [ 92.9987, 127.6374]], grad_fn=<AddBackward0>)

In [ ]:
#### Targets

targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
################   linear regression using pytorch built-ins     ######################

#  wh have linear regression & gradient descent model using some basic tensor operations. hoever, since this is a common pattern in deep learning, pytorch provides several buit-in
# functions and classes to make it easy to create and train models with just a few lines of code. lets begin by importing the torch.nn package from pytorch, which contains utiluty
# classes for building neural networks.


In [ ]:
import torch.nn as nn

In [ ]:
# input (temp, rainfall, humidity)

inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],dtype='float32')

In [ ]:
### Targets  (apples and orages)

targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]], dtype = 'float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
print(inputs)

print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [ ]:
#### Dataset and DataLoader

### we will create a tensordataset, which allows access to rows from inputs and targets as tuples , and provides standard apis for working with many different types of datasets
### in pytorch.

In [ ]:
#### import tensorDataset

from torch.utils.data import TensorDataset

In [ ]:
### Define dataset

train_ds = TensorDataset(inputs , targets)
train_ds[0:5]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [ ]:
#########  Creating DataLoader  ############

### we will also create a DataLoader, which can split the data into batches of a predefined size while training. it also provides other
#utilities like shuffling and random sampling of data.

In [ ]:
###########  import DataLoader ################

from torch.utils.data import DataLoader

In [ ]:
###  Define Data Loader

batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
len(train_dl)


3

In [ ]:
first_batch = next(iter(train_dl))
print(first_batch)

[tensor([[103.,  43.,  36.],
        [ 91.,  87.,  65.],
        [ 68.,  97.,  70.],
        [ 87., 134.,  58.],
        [ 74.,  66.,  43.]]), tensor([[ 20.,  38.],
        [ 80., 102.],
        [102., 120.],
        [119., 133.],
        [ 57.,  69.]])]


In [ ]:
### we can use the data loader in a for loop. lets look at an example.

In [ ]:
inputs


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [ ]:
targets


tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
for xb, yb  in train_dl:     ### xb = input_batches      yb= target_batches
  print(xb)
  print(yb)
  break

tensor([[ 91.,  88.,  64.],
        [ 73.,  66.,  44.],
        [ 68.,  97.,  70.],
        [ 68.,  96.,  71.],
        [101.,  44.,  37.]])
tensor([[ 81., 101.],
        [ 57.,  69.],
        [102., 120.],
        [104., 118.],
        [ 21.,  38.]])


In [ ]:
### nn.linear ####

### instead of initializing the weights & biases manually, we can define the model using the nn.linear class from pytorch, which does it automatically.

In [ ]:
# define model

model = nn.Linear(3, 2)   ### 3 column 2 row for inputs &&&& the last 2 represents : 2 biases and also 3=inputs & 2=outputs
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2457, -0.3096,  0.0206],
        [-0.3916, -0.4526, -0.4563]], requires_grad=True)
Parameter containing:
tensor([ 0.5277, -0.0889], requires_grad=True)


In [ ]:
### pytorch models also have a helful .parameters method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression
#### model, we have one weight matrix and one bias matrix.

In [ ]:
#### Parameters   it means how many features are there in a model like weights and biases etc

list(model.parameters())

[Parameter containing:
 tensor([[ 0.2457, -0.3096,  0.0206],
         [-0.3916, -0.4526, -0.4563]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5277, -0.0889], requires_grad=True)]

In [ ]:
### Generate predictions

preds = model(inputs)
preds


tensor([[  -1.3986,  -78.6224],
        [  -3.0468, -104.7586],
        [ -18.3952, -121.2714],
        [  13.0334,  -76.3808],
        [ -10.8052, -102.5008],
        [  -0.8433,  -78.5615],
        [  -2.7166, -104.7624],
        [ -18.1290, -122.1194],
        [  12.4781,  -76.4417],
        [ -11.0303, -102.5655],
        [  -1.0684,  -78.6261],
        [  -2.4915, -104.6977],
        [ -18.7254, -121.2677],
        [  13.2586,  -76.3161],
        [ -11.3605, -102.5618]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
### Loss >>> instead of defining a loss funtion manually, we can use the built-in loss function mse_lose

### import nn.functional


import torch.nn.functional as F

In [ ]:
### nn.functional package contains many usefull loss functions and seeral other utilities.


### Define Loss Function

loss_fn = F.mse_loss

In [ ]:
### let's compute the loss for the current predictions of our model.


loss = loss_fn(model(inputs) , targets)

print(loss)

tensor(23323.1680, grad_fn=<MseLossBackward0>)


In [ ]:
################## Optimization   ################

##instead of manipulating the models weights and biases using gradients we can use the optimizer optim.SGD SGD is short for stochastic gradient descent,
# the term stochastic (randomly selected batches) indicates that samples are selected in random batches instead of as a single group.



### Define Optimizer

opt = torch.optim.SGD(model.parameters(), lr= 1e-5)

In [ ]:
##############################    All steps in one function  #####################

### the only change is that we will work batches of data instead of processing the entire training data in every iteration. let's define a utility function fit
###that trains the model for a given number of epochs

In [ ]:
############ Utility function to train the model  ##############33

def fit(num_epochs, model, loss_fn, opt, train_dl):


  # repeat for given number of epochs
  for epoch in range(num_epochs):

    #Train with batches of data
    for xb, yb in train_dl:

      # 1. generate predictions
      pred = model(xb)

      # 2. calculate loss
      loss = loss_fn(pred, yb)

      # 3. compute gradients
      loss.backward()

      # 4. update parameters using gradients
      opt.step()

      # 5. reset the gradients to zero
      opt.zero_grad()


        # print the progress
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], LOSS: {:.4f}'.format(epoch+1, num_epochs, loss.item()))  ### that prints the loss from the last batch of data for every 10th epoch to track training progress.

In [ ]:
####  pass the parameters ##########

fit(100 , model, loss_fn, opt, train_dl)

Epoch [10/100], LOSS: 14.5961
Epoch [20/100], LOSS: 9.2249
Epoch [30/100], LOSS: 10.2218
Epoch [40/100], LOSS: 4.7474
Epoch [50/100], LOSS: 7.7360
Epoch [60/100], LOSS: 6.9036
Epoch [70/100], LOSS: 12.6845
Epoch [80/100], LOSS: 6.8621
Epoch [90/100], LOSS: 6.8979
Epoch [100/100], LOSS: 3.6843


In [ ]:
#### enerate Predictions

preds = model(inputs)

preds

tensor([[ 58.8491,  71.8574],
        [ 81.6125,  97.6322],
        [117.0833, 137.7507],
        [ 30.3860,  45.3866],
        [ 95.5789, 108.9246],
        [ 57.8221,  70.8652],
        [ 81.2570,  97.0962],
        [117.3246, 138.0522],
        [ 31.4131,  46.3787],
        [ 96.2505, 109.3808],
        [ 58.4936,  71.3214],
        [ 80.5855,  96.6401],
        [117.4388, 138.2867],
        [ 29.7145,  44.9304],
        [ 96.6060, 109.9168]], grad_fn=<AddmmBackward0>)

In [ ]:
### compare with targets
targets


tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [ ]:
model(torch.tensor([[37., 10, 26]]))   # test the model on zhob city

tensor([[12.5539, 16.0556]], grad_fn=<AddmmBackward0>)

In [ ]:
from sklearn.metrics import accuracy_score
preds.extend(preds.cpu().detach().numpy())  # Use detach() here
targets.extend(targets.numpy())
accuracy = accuracy_score(targets, preds)

AttributeError: ignored